### ISSUE TITLE
JSON parsing error on API call to associate phone with user

### ISSUE THREAD

**Issue by tfrancois** [duosecurity/duo_api_nodejs#45]
When I try to associate a newly created phone with a user successfully created seconds before, I get this error from this library:

>SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\ProgramData\npm\node_modules\@duosecurity\duo_api\lib\main.js:74:19
    at IncomingMessage.<anonymous> (C:\ProgramData\npm\node_modules\@duosecurity\duo_api\lib\main.js:61:7)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

This is a result of the response (data) being returned in HTML when this library is expecting a data response in JSON format.

> <html>
> <head><title>400 Bad Request</title></head>
> <body>
> <center><h1>400 Bad Request</h1></center>
> <hr><center>Duo/1.0</center>
> </body>
> </html>

Not sure if the error is because I am trying to associate so soon after creating the user and the phone, BUT if that's the case I should get a proper response back from the API.  Currently it crashes my app because of this JSON.parse error (line 74 in \lib\main.js. 

Can we fix this please?

FYI: I have made sure that I am passing the valid user_id and phone_id when I call the POST operation to /admin/v1/users/<user_id>/phones so not exactly sure what the issue is other than timing.  Thanks!

**Comment by tfrancois** [comment]
Upon further testing, I was not passing the lead '/' slash in the '/admin/v1/users'  path, but nevertheless this API should return a better response (indicating the bad path) rather than accepting the invalid path and then expecting a JSON result after the call is attempted with the malformed path value.  Now it explains why it wasn't previously reported by another user - but i figured I would leave it open in case the devs want to address it.
